### ISSUE TITLE
Trying to build gnat-fsf-13 on Mac

### ISSUE THREAD

**Issue by simonjwright** [alire-project/GNAT-FSF-builds#54]
Building on MacBook Pro 13" early 2015 running Monterey 12.6.9/Command Line Tools 14.2/Python 3.9/GCC 12.2.0.

Trying to build GMP with e3-core 22.1.0, per README:
```
DEBUG    initialize spec repository (/Volumes/Miscellaneous3/GNAT-FSF-builds/specs)
DEBUG    found 31 specs
DEBUG    found 0 yaml files API 1.4 compatible
Traceback (most recent call last):
  File "/Volumes/Miscellaneous3/GNAT-FSF-builds/./anod", line 71, in <module>
    exit(do_build(m))
  File "/Volumes/Miscellaneous3/GNAT-FSF-builds/lib/anod_build.py", line 81, in do_build
    sbx = create_anod_sandbox(m.args.sandbox_dir, SPEC_DIR)
  File "/Volumes/Miscellaneous3/GNAT-FSF-builds/lib/anod/util.py", line 38, in create_anod_sandbox
    sbx = SandBox(sbx_dir)
TypeError: __init__() takes 1 positional argument but 2 were given
```

Trying with e3-core == 22.3.1 gets a bit further:
```
DEBUG    initialize spec repository (/Volumes/Miscellaneous3/GNAT-FSF-builds/specs)
DEBUG    found 31 specs
DEBUG    found 0 yaml files API 1.4 compatible
DEBUG    using alternate specs dir /Volumes/Miscellaneous3/GNAT-FSF-builds/specs
DEBUG    loading anod spec: gmp
DEBUG    loading anod spec: gnu
DEBUG    loading anod spec: gh-artifact
DEBUG    loading anod spec: common
DEBUG    loading anod spec: base_gcc
DEBUG    rm /Volumes/Miscellaneous3/GNAT-FSF-builds/sbx/fingerprints/download.gmp-6.2.1.tar.bz2.json
DEBUG    rm /Volumes/Miscellaneous3/GNAT-FSF-builds/sbx/fingerprints/source_get.gmp-6.2.1.tar.bz2.json
DEBUG    source_get.gmp-6.2.1.tar.bz2 has no previous fingerprint
INFO     [default    unknown      0s] get source gmp-6.2.1.tar.bz2
DEBUG    rm /Volumes/Miscellaneous3/GNAT-FSF-builds/sbx/fingerprints/x86_64-darwin.gmp.source_install.gmp-6.2.1.tar.bz2.json
DEBUG    rm /Volumes/Miscellaneous3/GNAT-FSF-builds/sbx/fingerprints/x86_64-darwin.base_gcc.build.json
DEBUG    rm /Volumes/Miscellaneous3/GNAT-FSF-builds/sbx/fingerprints/x86_64-darwin.gmp.build.json
DEBUG    rm /Volumes/Miscellaneous3/GNAT-FSF-builds/sbx/fingerprints/root.json
DEBUG    non-ready?: False, in queue: 0, running: 0
```

I think I should be able to build gcc, without bothering to build gmp, mpfr etc separately first? (I have the same problem there).

**Comment by Fabien-Chouteau** [comment]
Hi @simonjwright ,

That's strange, I do have `e3-core 22.1.0` on my Linux setup and it works. 

> I think I should be able to build gcc, without bothering to build gmp, mpfr etc separately first? (I have the same problem there).

These libs are required for the build of GCC, that's why the script will try to build them first.

**Comment by simonjwright** [comment]
> Hi @simonjwright ,
> 
> That's strange, I do have `e3-core 22.1.0` on my Linux setup and it works.
> 
> > I think I should be able to build gcc, without bothering to build gmp, mpfr etc separately first? (I have the same problem there).
> 
> These libs are required for the build of GCC, that's why the script will try to build them first.

Oh yes -- what I meant was, do I have to do `anod build gmp` etc first? What I do is to use `contribs/download_prerequisites`, then the standard make builds them inline.

**Comment by Fabien-Chouteau** [comment]
> I seem to remember you having trouble building on your mac mini?

Indeed, the machine reboots during the build for whatever reason...
 
> Oh yes -- what I meant was, do I have to do `anod build gmp` etc first? What I do for my own builds is to use `contribs/download_prerequisites`, then the standard make builds them inline.

Ok, I am used to manage the builds this way.

You can remove the build deps in the GCC spec if you want:
https://github.com/alire-project/GNAT-FSF-builds/blob/d59ac88a3b47e1ccff831f5f4c5296473f815014/specs/gcc.anod#L61

**Comment by Fabien-Chouteau** [comment]
It works! I changed the specs to explicitly set the number of jobs and the build now pass even on GitHub CI :partying_face: 
Thanks so much @simonjwright. 

The binaries are here: https://github.com/alire-project/GNAT-FSF-builds/releases/tag/gnat-13.1.0-1

I will try them out on my mac mini.

**Comment by Fabien-Chouteau** [comment]
The native compiler seems to work. Although I had to do `sudo xcode-select -switch /Library/Developer/CommandLineTools` to avoid an error with LLVM.

The arm cross compiler binutils on the other hand have a dependency on zstd.1.dylib which should be removed.
